version: 0.0
os: linux

files:             
  - source: /
    destination: /home/centos/deploy
hooks:
  ApplicationStart:
    - location: infrastructure/aws/codedeploy/startApp.sh
      timeout: 3600
      runas: centos
  ApplicationStop:
   - location: infrastructure/aws/codedeploy/stopApp.sh
     timeout: 3600
     runas: centos
