version: 0.0

os: linux
files:
  - source: /
    destination: /home/centos/webapp/
hooks:
  AfterInstall:
    - location: /afterInstall.sh
      timeout: 600
      runas: centos
  ApplicationStart:
    - location: /startApp.sh
      timeout: 600
      runas: centos
