version: 0.0
os: linux

files:             
  - source: ~/
    destination: /home/centos/myproject

hooks:
  AfterInstall:
   - location: ./infrastructure/aws/codedeploy/afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
    - location: ./infrastructure/aws/codedeploy/startApp.sh
      timeout: 3600
      runas: centos
