version: 0.0
os: linux

files:             
  - source: /webapp.zip
    destination: /

hooks:
  BeforeInstall:
    - location: ./beforeInstall.sh
      runas: centos
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
    - location: myproject/startApp.sh
      timeout: 3600
      runas: centos