version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-jessie
      - image: circleci/mysql:8.0.3
    steps:
      - checkout
      - run:
          name: Install packages
          command: sudo yum -y update
            sudo yum -y install zip
            sudo yum -y install unzip
            sudo yum -y install yum-utils
            sudo yum -y groupinstall development
            sudo yum -y install https://centos7.iuscommunity.org/ius-release.rpm
            sudo yum -y install python36u python36u-pip
            sudo yum -y install python-virtualenv
            sudo yum -y install epel-release
            sudo yum -y install python-virtualenv
            sudo yum –y update
            mkdir myproject
            cd myproject
            mkdir Images
            python3.6 -m venv venv
            . venv/bin/activate
      - run:
          name: Python dependencies
          command: sudo yum -y install sqlite
            sudo pip3.6 install pybase64
            sudo pip3.6 install bcrypt
            sudo pip3.6 install SQLAlchemy
            sudo pip3.6 install Flask
            sudo pip3.6 install uuid
            sudo pip3.6 install Flask-SQLAlchemy
            sudo pip3.6 install password-strength
            sudo yum -y install python36u-devel
            sudo yum -y install nano
            sudo pip3.6 install flask-mysql
            sudo pip3.6 install mysql
            sudo pip3.6 install boto3
      - run:
          name: Install awscli
          command: sudo pip3.6 install awscli
      - run:
          name: Download packer
          command: |
            wget -q https://releases.hashicorp.com/packer/1.3.4/packer_1.3.4_linux_amd64.zip 
            unzip packer*.zip  
            chmod +x packer
      - run:
          name: Validate Packer Template
          command: ./packer validate firstinstance.json
      - run:
          name: Build AMI
          command: |
            ./packer build \
            -var "aws_region=${AWS_REGION}" \
            -var "subnet_id=${AWS_SUBNET_ID}" \
            firstinstance.json