version: 2
jobs:
  build:
    branches:
      only:
        - trial
        - CloudWatch
        - cw2
        - cw3
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - run:
          name: Build Artifact
          command: |
            cd webapp
            ls -al
            cd ..
      - run:
          name: Install awscli
          command: |
            sudo pip3.6 install awscli
            aws configure set aws_access_key_id $aws_access_key_id
            aws configure set aws_secret_access_key $aws_secret_access_key
            aws configure set region $region
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            mkdir -p codedeploy_artifact
            cd webapp && zip -r ~/webapp-${CIRCLE_BUILD_NUM}.zip *
            cd ..   
            mv ~/webapp-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
            cd codedeploy_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al
 
      - run:
          name: list directory
          command: |
            cd ~/ && ls
      - run:
          name: Upload Artifact to S3
          command: |
            echo "Hello"
            ls -al
            aws s3 sync codedeploy_artifact s3://$s3_bucket_name
            echo "Uploaded to s3"
      - run:
          name: Make CodeDeploy API call
          command: |
            aws configure set region us-east-1 && aws deploy create-deployment --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name csye6225-webapp-deployment --description "My demo deployment" --s3-location bucket=$s3_bucket_name,bundleType=zip,key=webapp-${CIRCLE_BUILD_NUM}.zip
