version: 2
jobs:
  build:
    branches:
      only:
        - assignment6
        
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - run:
          name: Build Artifact
          command: |
            cd webapp
            ls -al
            cd ../..	
      - run:
          name: Install awscli
          command: |
            sudo pip3.6 install awscli
            aws configure set aws_access_key_id $aws_access_key_id
            aws configure set aws_secret_access_key $aws_secret_access_key
            aws configure set region $region
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            zip -r ~/webapp.zip *
            ls -l
      - run:
          name: Upload Artifact to S3
          command: |
            echo "Hello"
            aws s3 cp ~/webapp.zip s3://$s3_bucket_name
            echo "Uploaded to s3"
      - run:
          name: Make CodeDeploy API call
          command: |
            aws configure set region us-east-1 && aws deploy create-deployment --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name csye6225-webapp-deployment --description "My demo deployment" --s3-location bucket=$s3_bucket_name,bundleType=zip,key=webapp.zip  




#aa
