version: 2
jobs:
  build:
    branches:
      only:
        - assignment5
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - run:
          name: Build artifacts
          command: |
            cd webapp
            cd ..
      - run:
          name: Zip artifacts
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            zip ~/webapp.zip . -i ~/webapp
            ls -al
      - run:
          name: Upload artifacts to s3
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            aws s3 cp ~/webapp.zip s3://code-deploy.csye6225-su19-deogade.me/
      
