version: 2
jobs:
  build:
    branches:
      only:
        - assignment5
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - run:
          name: Build Artifact
          command: |
            cd webapp
            ls -al
            cd ..
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            cd webapp && zip -r ~/webapp.zip . -i *
      - run:
          name: Upload Artifact to S3
          command: |
            echo "Hello"
      - run:
          name: Make CodeDeploy API call
          command: |
            echo "Hello CodeDeploy"
  deploy:
    machine:
      enabled: true
    working_directory: ~/circle-tmp-folder
    steps:
       - run:
          name: Deploy
          command: aws s3 cp ~/webapp.zip s3://code-deploy.csye6225-su19-deogade.me/Project
      