version: 2
jobs:
  build:
    working_directory: ~/webapp
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - run:
          name: List directory
          command: |
            cd webapp && ls
            cd .. && ls
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Zip Project 
          command: zip -r ~/webapp.zip * 
      - run:
          name: List directory
          command: cd ~/ && ls
      - run:
          name: Send WebApp to S3
          command: aws s3 cp ~/webapp.zip s3://$S3_BUCKET
      - run: 
          name: Deploy to AWS EC2
          command: aws configure set region us-east-1 && aws deploy create-deployment --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name csye6225-webapp-deployment --description "My demo deployment" --s3-location bucket=$S3_BUCKET,bundleType=zip,key=webapp.zip 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
              branches:
                only: 
                  - assignment6