version: 2
jobs:
  build:
    branches:
      only:
        - assignment5
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - run:
          name: Build Artifact
          command: |
            cd webapp
            ls -al
            cd ..
      - run:
          name: Install awscli
          command: |
            sudo pip3.6 install awscli
            aws configure set aws_access_key_id $aws_access_key_id
            aws configure set aws_secret_access_key $aws_secret_access_key
            aws configure set region $region
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            cd webapp && zip -r ~/webapp.zip *
      - run:
          name: Upload Artifact to S3
          command: |
            echo "Hello"
            aws s3 cp ~/webapp.zip s3://code-deploy.csye6225-su19-deogade.me
            echo "Uploaded to s3"
      - run:
          name: Make CodeDeploy API call
          command: |
            echo "Hello CodeDeploy"
  # deploy:
  #   machine:
  #     enabled: true
  #   working_directory: ~/
  #   steps:
  #      - run:
  #         name: Deploy
  #         command: aws s3 cp ~/webapp.zip s3://code-deploy.csye6225-su19-deogade.me
  #     