AWSTemplateFormatVersion: 2010-09-09
Resources:





  AWScodedeployEC2toS3:

    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CodeDeploy-EC2-S3
     
      
      PolicyDocument:     
        
            
        Version: 2012-10-17
        Statement:
          -
          
            Action: 
              
              - "s3:Get*"
              - "s3:List*"

               
                
            Effect: Allow
            Resource: arn:aws:s3:::code-deploy.csye6225-su19-patilsup.me
      Users: 
        - circleci 
            
        
  CircleCIUploadToS3:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "CircleCI-Upload-To-S3"
     
      
      PolicyDocument:     
        
        Version: 2012-10-17
        Statement: 
          - 
            
            Effect: Allow
            Action: s3:PutObject
                
            Resource: "arn:aws:s3:::code-deploy.csye6225-su19-patilsup.me"
               
      Users: 
        - circleci 
            

  CirlceCICodeDeploy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CirlceCI-Code-Deploy
     
      
      PolicyDocument:     
        
        Version: 2012-10-17
        Statement:
          -
          
           
        
            Effect: Allow
            Action:
              - codedeploy:RegisterApplicationRevision
              - codedeploy:GetApplicationRevision
          
            Resource: arn:aws:codedeploy:us-east-1:419412470032:application:csye6225-webapp
          
            Effect: Allow
            Action:
              
              - codedeploy:CreateDeployment
              - codedeploy:GetDeployment
          
            Resource: "*"
        
            Effect: Allow
            Action: codedeploy:GetDeploymentConfig
          
            Resource:
              - 
                arn:aws:codedeploy:us-east-1:419412470032:deploymentconfig:CodeDeployDefault.OneAtATime
                arn:aws:codedeploy:us-east-1:419412470032:deploymentconfig:CodeDeployDefault.HalfAtATime
                arn:aws:codedeploy:us-east-1:419412470032:deploymentconfig:CodeDeployDefault.AllAtOnce
          
               
      Users: 
        - circleci 


  circleciec2ami:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: circleci-ec2-ami
     
      
      PolicyDocument:     
        
        Version: 2012-10-17
        Statement:
          - 
          
            
           
            Effect: Allow
            Action:
               
              - "ec2:AttachVolume"
              - "autoscaling:CompleteLifecycleAction"
              - "autoscaling:DeleteLifecycleHook"
              - "autoscaling:DescribeAutoScalingGroups"
              - "autoscaling:DescribeLifecycleHooks"
              - "autoscaling:PutLifecycleHook"
              - "autoscaling:RecordLifecycleActionHeartbeat"
              - "autoscaling:CreateAutoScalingGroup"
              - "autoscaling:UpdateAutoScalingGroup"
              - "autoscaling:EnableMetricsCollection"
              - "autoscaling:DescribeAutoScalingGroups"
              - "autoscaling:DescribePolicies"
              - "autoscaling:DescribeScheduledActions"
              - "autoscaling:DescribeNotificationConfigurations"
              - "autoscaling:DescribeLifecycleHooks"
              - "autoscaling:SuspendProcesses"
              - "autoscaling:ResumeProcesses"
              - "autoscaling:AttachLoadBalancers"
              - "autoscaling:PutScalingPolicy"
              - "autoscaling:PutScheduledUpdateGroupAction"
              - "autoscaling:PutNotificationConfiguration"
              - "autoscaling:PutLifecycleHook"
              - "autoscaling:DescribeScalingActivities"
              - "autoscaling:DeleteAutoScalingGroup"
              - "ec2:DescribeInstances"
              - "ec2:DescribeInstanceStatus"
              - "ec2:TerminateInstances"
              - "tag:GetTags"
              - "tag:GetResources"
              - "sns:Publish"
              - "cloudwatch:DescribeAlarms"
              - "cloudwatch:PutMetricAlarm"
              - "elasticloadbalancing:DescribeLoadBalancers"
              - "elasticloadbalancing:DescribeInstanceHealth"
              - "elasticloadbalancing:RegisterInstancesWithLoadBalancer"
              - "elasticloadbalancing:DeregisterInstancesFromLoadBalancer"
              - "elasticloadbalancing:DescribeTargetGroups"
              - "elasticloadbalancing:DescribeTargetHealth"
              - "elasticloadbalancing:RegisterTargets"
              - "elasticloadbalancing:DeregisterTargets"
            
          
        




      


        
   
      
                
          
            Resource: "*"
      
               
      Users: 
        - circleci 
            


  AWSCodedeploy:
    Type: AWS::CodeDeploy::Application
    Properties: 
      ApplicationName: csye6225-webapp
      ComputePlatform: Server



          
        

      
          












  


   
  