version: 0.0

os: linux
files:
  - source: /
    destination: /home/centos/webapp
hooks:
  BeforeInstall:
    - location: cdScripts/cleanServer.sh
      timeout: 600
      runas: centos
  AfterInstall:
    - location: cdScripts/installOSDependencies.sh
      timeout: 600
      runas: centos
    - location: cdScripts/installPythonDependencies.sh
      timeout: 600
      runas: centos
  ApplicationStart:
    - location: cdScripts/startApp.sh
      timeout: 600
      runas: centos
