version: 0.0

os: linux
files:
  - source: /
    destination: /home/centos/webapp/webapp
hooks:
  AfterInstall:
    - location: cdScripts/afterInstall.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: cdScripts/startApp.sh
      timeout: 600
      runas: root
